#!/bin/bash

# ================================================
# E-RAPORT PER-FEATURE COLLECTOR v1
# ================================================
# Interactive picker — pilih feature mana yang mau di-collect.
#
# Mode tersedia:
#   1. ADMIN          → Master Data, Akademik, Sistem
#   2. USER           → Penilaian / Input Nilai harian
#   3. RAPOR          → Cetak / Preview / ZIP archive
#   4. AUTH           → Login flow + auth callback
#   5. SHARED CORE    → Layout, providers, hooks dasar, types
#   6. ALL FEATURES   → Gabungan semua (1 file per feature)
#
# Usage:
#   ./collect-per-feat.sh              # interactive menu
#   ./collect-per-feat.sh admin        # langsung admin
#   ./collect-per-feat.sh user         # langsung user
#   ./collect-per-feat.sh rapor        # langsung rapor
#   ./collect-per-feat.sh auth         # langsung auth
#   ./collect-per-feat.sh shared       # langsung shared core
#   ./collect-per-feat.sh all          # collect semua feature
#
# OUTPUT: collection/collected-<feature>.txt
# ================================================

# ── Colors ──────────────────────────────────────
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
MAGENTA='\033[0;35m'
BOLD='\033[1m'
NC='\033[0m'

# ── Paths ────────────────────────────────────────
WORKSPACE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$WORKSPACE_ROOT/src"
COLLECTION_DIR="$WORKSPACE_ROOT/collection"

# ── State (per run) ──────────────────────────────
SKIPPED=0
COLLECTED=0
CURRENT_OUT=""

# ── Init ─────────────────────────────────────────
mkdir -p "$COLLECTION_DIR"

# ── Helpers ──────────────────────────────────────

init_output() {
    local feature="$1"
    local description="$2"
    CURRENT_OUT="$COLLECTION_DIR/collected-${feature}.txt"
    SKIPPED=0
    COLLECTED=0

    {
        echo "# E-RAPORT - ${description}"
        echo "# Generated by collect-per-feat.sh"
        echo ""
        echo "---"
        echo ""
    } > "$CURRENT_OUT"
}

section() {
    local icon="$1"
    local label="$2"
    echo ""
    echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BOLD}${BLUE}${icon} ${label}${NC}"
    echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo "" >> "$CURRENT_OUT"
    echo "# ${icon} ${label}" >> "$CURRENT_OUT"
    echo "" >> "$CURRENT_OUT"
}

collect_file() {
    local file="$1"
    local rel="${file#$WORKSPACE_ROOT/}"
    local ext="${file##*.}"

    if [ ! -f "$file" ]; then
        echo -e "  ${RED}✗ SKIP${NC} ${YELLOW}(not found)${NC}: $rel"
        SKIPPED=$((SKIPPED + 1))
        return
    fi

    local lines
    lines=$(wc -l < "$file" 2>/dev/null)
    lines="${lines// /}"

    echo -e "  ${GREEN}✓${NC} $rel ${CYAN}(${lines} lines)${NC}"
    COLLECTED=$((COLLECTED + 1))

    echo "" >> "$CURRENT_OUT"
    echo "## \`${rel}\`" >> "$CURRENT_OUT"
    echo "" >> "$CURRENT_OUT"
    echo "**Lines:** ${lines}" >> "$CURRENT_OUT"
    echo "" >> "$CURRENT_OUT"
    echo '```'"${ext}" >> "$CURRENT_OUT"
    cat "$file" >> "$CURRENT_OUT"
    echo "" >> "$CURRENT_OUT"
    echo '```' >> "$CURRENT_OUT"
    echo "" >> "$CURRENT_OUT"
    echo "---" >> "$CURRENT_OUT"
    echo "" >> "$CURRENT_OUT"
}

print_summary() {
    local feature="$1"
    echo ""
    echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BOLD}${GREEN}✅ SELESAI - ${feature^^}${NC}"
    echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    echo -e "${GREEN}📄 Output    :${NC} $CURRENT_OUT"
    echo -e "${CYAN}📝 Lines     :${NC} $(wc -l < "$CURRENT_OUT")"
    echo -e "${CYAN}📦 Size      :${NC} $(du -h "$CURRENT_OUT" | cut -f1)"
    echo -e "${GREEN}✓  Collected :${NC} $COLLECTED files"
    echo -e "${YELLOW}✗  Skipped   :${NC} $SKIPPED files (not found)"
    echo ""
}

# ================================================
# FEATURE: ADMIN
# ================================================
collect_admin() {
    init_output "admin" "Admin Features (Master Data, Akademik, Sistem)"

    section "🏠" "ADMIN ENTRY PAGE"
    collect_file "$SRC/app/(dashboard)/admin/page.tsx"

    section "🔑" "API ROUTES (Admin)"
    collect_file "$SRC/app/api/admin/users/route.ts"
    collect_file "$SRC/app/api/admin/users/[id]/route.ts"
    collect_file "$SRC/app/api/admin/users/[id]/password/route.ts"

    section "🏫" "ADMIN COMPONENTS"
    collect_file "$SRC/components/features/admin/index.ts"
    collect_file "$SRC/components/features/admin/tab-profil-pkbm.tsx"
    collect_file "$SRC/components/features/admin/tab-tahun-kelas.tsx"
    collect_file "$SRC/components/features/admin/tab-siswa.tsx"
    collect_file "$SRC/components/features/admin/tab-mata-pelajaran.tsx"
    collect_file "$SRC/components/features/admin/tab-p5-master.tsx"
    collect_file "$SRC/components/features/admin/tab-predikat.tsx"
    collect_file "$SRC/components/features/admin/tab-ekskul-preset.tsx"
    collect_file "$SRC/components/features/admin/tab-users.tsx"
    collect_file "$SRC/components/features/admin/enrollment-dialog.tsx"
    collect_file "$SRC/components/features/admin/import-siswa-dialog.tsx"
    collect_file "$SRC/components/features/admin/tanggal-cetak-paket-form.tsx"
    collect_file "$SRC/components/features/admin/tanggal-cetak-warning-badge.tsx"

    section "🎣" "ADMIN HOOKS"
    collect_file "$SRC/hooks/index.ts"
    collect_file "$SRC/hooks/use-satuan-pendidikan.ts"
    collect_file "$SRC/hooks/use-tahun-pelajaran.ts"
    collect_file "$SRC/hooks/use-kelas.ts"
    collect_file "$SRC/hooks/use-siswa.ts"
    collect_file "$SRC/hooks/use-enrollment.ts"
    collect_file "$SRC/hooks/use-mata-pelajaran.ts"
    collect_file "$SRC/hooks/use-kompetensi.ts"
    collect_file "$SRC/hooks/use-p5-master.ts"
    collect_file "$SRC/hooks/use-predikat.ts"
    collect_file "$SRC/hooks/use-ekskul-preset.ts"
    collect_file "$SRC/hooks/use-users.ts"
    collect_file "$SRC/hooks/use-tanggal-cetak-paket.ts"
    collect_file "$SRC/hooks/use-is-desktop.ts"
    collect_file "$SRC/hooks/use-auth.ts"

    section "🗄️" "SUPABASE LIB"
    collect_file "$SRC/lib/supabase/client.ts"
    collect_file "$SRC/lib/supabase/server.ts"
    collect_file "$SRC/lib/supabase/admin.ts"
    collect_file "$SRC/lib/supabase/proxy.ts"

    section "🔀" "PROXY"
    collect_file "$SRC/proxy.ts"

    section "📚" "LIB & UTILS"
    collect_file "$SRC/lib/auth-guard.ts"
    collect_file "$SRC/lib/validators.ts"
    collect_file "$SRC/lib/utils.ts"
    collect_file "$SRC/lib/query-client.ts"

    section "📝" "TYPES"
    collect_file "$SRC/types/index.ts"
    collect_file "$SRC/types/database.ts"

    section "⚙️" "CONSTANTS"
    collect_file "$SRC/constants/index.ts"
    collect_file "$SRC/constants/routes.ts"

    section "🗃️" "STORES"
    collect_file "$SRC/stores/index.ts"
    collect_file "$SRC/stores/auth-store.ts"

    print_summary "admin"
}

# ================================================
# FEATURE: USER (PENILAIAN)
# ================================================
collect_user() {
    init_output "user" "User Features (Penilaian / Input Nilai harian)"

    section "📁" "APP ROOT"
    collect_file "$SRC/app/layout.tsx"
    collect_file "$SRC/app/page.tsx"
    collect_file "$SRC/app/globals.css"

    section "🏠" "DASHBOARD SHELL & PROFILE"
    collect_file "$SRC/app/(dashboard)/layout.tsx"
    collect_file "$SRC/app/(dashboard)/profile/page.tsx"

    section "📝" "PENILAIAN PAGES"
    collect_file "$SRC/app/(dashboard)/penilaian/page.tsx"
    collect_file "$SRC/app/(dashboard)/penilaian/[kelasId]/page.tsx"
    collect_file "$SRC/app/(dashboard)/penilaian/[kelasId]/[enrollmentId]/page.tsx"

    section "📝" "PENILAIAN COMPONENTS"
    collect_file "$SRC/components/features/penilaian/index.ts"
    collect_file "$SRC/components/features/penilaian/kelas-list.tsx"
    collect_file "$SRC/components/features/penilaian/siswa-list.tsx"
    collect_file "$SRC/components/features/penilaian/nilai-form.tsx"
    collect_file "$SRC/components/features/penilaian/nilai-detail-drawer.tsx"
    collect_file "$SRC/components/features/penilaian/p5-form.tsx"
    collect_file "$SRC/components/features/penilaian/p5-detail-drawer.tsx"
    collect_file "$SRC/components/features/penilaian/absensi-catatan-form.tsx"
    collect_file "$SRC/components/features/penilaian/ekskul-form.tsx"
    collect_file "$SRC/components/features/penilaian/quick-fill-inline.tsx"
    collect_file "$SRC/components/features/penilaian/quick-fill-panel.tsx"
    collect_file "$SRC/components/features/penilaian/quick-fill-dialog.tsx"
    collect_file "$SRC/components/features/penilaian/quick-fill-simple-dialog.tsx"

    section "🎨" "LAYOUT COMPONENTS"
    collect_file "$SRC/components/layout/index.ts"
    collect_file "$SRC/components/layout/header.tsx"
    collect_file "$SRC/components/layout/app-sidebar.tsx"
    collect_file "$SRC/components/layout/mobile-nav.tsx"
    collect_file "$SRC/components/layout/user-menu.tsx"
    collect_file "$SRC/components/layout/nav-config.ts"

    section "🧩" "PROVIDERS & SHARED"
    collect_file "$SRC/components/providers/index.ts"
    collect_file "$SRC/components/providers/auth-provider.tsx"
    collect_file "$SRC/components/providers/query-provider.tsx"
    collect_file "$SRC/components/shared/index.ts"
    collect_file "$SRC/components/shared/confirm-dialog.tsx"
    collect_file "$SRC/components/shared/loading-spinner.tsx"
    collect_file "$SRC/components/shared/offline-detector.tsx"

    section "🎣" "HOOKS"
    collect_file "$SRC/hooks/index.ts"
    collect_file "$SRC/hooks/use-auth.ts"
    collect_file "$SRC/hooks/use-is-desktop.ts"
    collect_file "$SRC/hooks/use-satuan-pendidikan.ts"
    collect_file "$SRC/hooks/use-tahun-pelajaran.ts"
    collect_file "$SRC/hooks/use-kelas.ts"
    collect_file "$SRC/hooks/use-siswa.ts"
    collect_file "$SRC/hooks/use-enrollment.ts"
    collect_file "$SRC/hooks/use-mata-pelajaran.ts"
    collect_file "$SRC/hooks/use-kompetensi.ts"
    collect_file "$SRC/hooks/use-p5-master.ts"
    collect_file "$SRC/hooks/use-predikat.ts"
    collect_file "$SRC/hooks/use-ekskul-preset.ts"
    collect_file "$SRC/hooks/use-nilai.ts"
    collect_file "$SRC/hooks/use-rapor.ts"

    section "🗄️" "SUPABASE LIB"
    collect_file "$SRC/lib/supabase/client.ts"
    collect_file "$SRC/lib/supabase/server.ts"
    collect_file "$SRC/lib/supabase/proxy.ts"

    section "🔀" "PROXY"
    collect_file "$SRC/proxy.ts"

    section "📚" "LIB & UTILS"
    collect_file "$SRC/lib/utils.ts"
    collect_file "$SRC/lib/query-client.ts"
    collect_file "$SRC/lib/validators.ts"
    collect_file "$SRC/lib/quick-fill.ts"
    collect_file "$SRC/lib/quick-fill-absensi.ts"
    collect_file "$SRC/lib/quick-fill-ekskul.ts"
    collect_file "$SRC/lib/quick-fill-p5.ts"

    section "📝" "TYPES"
    collect_file "$SRC/types/index.ts"
    collect_file "$SRC/types/database.ts"

    section "⚙️" "CONSTANTS"
    collect_file "$SRC/constants/index.ts"
    collect_file "$SRC/constants/routes.ts"

    section "🗃️" "STORES"
    collect_file "$SRC/stores/index.ts"
    collect_file "$SRC/stores/auth-store.ts"

    print_summary "user"
}

# ================================================
# FEATURE: RAPOR (CETAK/PREVIEW)
# ================================================
collect_rapor() {
    init_output "rapor" "Rapor Cetak/Preview (PDF + ZIP archive)"

    section "🏠" "LAYOUT SHELL"
    collect_file "$SRC/app/layout.tsx"
    collect_file "$SRC/app/(dashboard)/layout.tsx"

    section "📊" "RAPOR PAGES"
    collect_file "$SRC/app/(dashboard)/rapor/page.tsx"
    collect_file "$SRC/app/(dashboard)/rapor/[enrollmentId]/page.tsx"

    section "🖨️" "PRINT / CETAK"
    collect_file "$SRC/app/(print)/layout.tsx"
    collect_file "$SRC/app/(print)/cetak/[enrollmentId]/page.tsx"

    section "📊" "RAPOR COMPONENTS"
    collect_file "$SRC/components/features/rapor/index.ts"
    collect_file "$SRC/components/features/rapor/rapor-pdf-document.tsx"
    collect_file "$SRC/components/features/rapor/rapor-pdf-styles.ts"
    collect_file "$SRC/components/features/rapor/rapor-pdf-viewer.tsx"
    collect_file "$SRC/components/features/rapor/rapor-kelas-list.tsx"
    collect_file "$SRC/components/features/rapor/rapor-kelas-drawer.tsx"
    collect_file "$SRC/components/features/rapor/export-zip-dialog.tsx"

    section "🎨" "LAYOUT COMPONENTS"
    collect_file "$SRC/components/layout/index.ts"
    collect_file "$SRC/components/layout/app-sidebar.tsx"
    collect_file "$SRC/components/layout/mobile-nav.tsx"
    collect_file "$SRC/components/layout/nav-config.ts"

    section "🧩" "PROVIDERS & SHARED"
    collect_file "$SRC/components/providers/index.ts"
    collect_file "$SRC/components/providers/auth-provider.tsx"
    collect_file "$SRC/components/providers/query-provider.tsx"
    collect_file "$SRC/components/shared/index.ts"
    collect_file "$SRC/components/shared/loading-spinner.tsx"

    section "🎣" "HOOKS"
    collect_file "$SRC/hooks/index.ts"
    collect_file "$SRC/hooks/use-auth.ts"
    collect_file "$SRC/hooks/use-is-desktop.ts"
    collect_file "$SRC/hooks/use-rapor.ts"
    collect_file "$SRC/hooks/use-enrollment.ts"
    collect_file "$SRC/hooks/use-kelas.ts"
    collect_file "$SRC/hooks/use-tahun-pelajaran.ts"
    collect_file "$SRC/hooks/use-tanggal-cetak-paket.ts"
    collect_file "$SRC/hooks/use-p5-master.ts"

    section "📚" "LIB - RAPOR"
    collect_file "$SRC/lib/export-rapor-zip.tsx"
    collect_file "$SRC/lib/p5-tree.ts"
    collect_file "$SRC/lib/utils.ts"
    collect_file "$SRC/lib/query-client.ts"

    section "🗄️" "SUPABASE LIB"
    collect_file "$SRC/lib/supabase/client.ts"
    collect_file "$SRC/lib/supabase/server.ts"
    collect_file "$SRC/lib/supabase/proxy.ts"

    section "🔀" "PROXY"
    collect_file "$SRC/proxy.ts"

    section "📝" "TYPES"
    collect_file "$SRC/types/index.ts"
    collect_file "$SRC/types/database.ts"

    section "⚙️" "CONSTANTS"
    collect_file "$SRC/constants/index.ts"
    collect_file "$SRC/constants/routes.ts"

    section "🗃️" "STORES"
    collect_file "$SRC/stores/index.ts"
    collect_file "$SRC/stores/auth-store.ts"

    print_summary "rapor"
}

# ================================================
# FEATURE: AUTH (login flow only)
# ================================================
collect_auth() {
    init_output "auth" "Auth Flow (Login + Logout + Session)"

    section "📁" "APP ROOT"
    collect_file "$SRC/app/layout.tsx"
    collect_file "$SRC/app/page.tsx"

    section "🔐" "AUTH PAGES"
    collect_file "$SRC/app/(auth)/layout.tsx"
    collect_file "$SRC/app/(auth)/login/page.tsx"
    collect_file "$SRC/app/api/auth/callback/route.ts"

    section "🔐" "AUTH COMPONENTS"
    collect_file "$SRC/components/features/auth/index.ts"
    collect_file "$SRC/components/features/auth/login-form.tsx"
    collect_file "$SRC/components/features/auth/logout-button.tsx"

    section "🎣" "AUTH HOOKS"
    collect_file "$SRC/hooks/use-auth.ts"

    section "🗄️" "SUPABASE LIB"
    collect_file "$SRC/lib/supabase/client.ts"
    collect_file "$SRC/lib/supabase/server.ts"
    collect_file "$SRC/lib/supabase/proxy.ts"

    section "🔀" "PROXY"
    collect_file "$SRC/proxy.ts"

    section "📚" "LIB & UTILS"
    collect_file "$SRC/lib/validators.ts"
    collect_file "$SRC/lib/utils.ts"

    section "📝" "TYPES"
    collect_file "$SRC/types/index.ts"
    collect_file "$SRC/types/database.ts"

    section "⚙️" "CONSTANTS"
    collect_file "$SRC/constants/index.ts"
    collect_file "$SRC/constants/routes.ts"

    section "🗃️" "STORES"
    collect_file "$SRC/stores/index.ts"
    collect_file "$SRC/stores/auth-store.ts"

    print_summary "auth"
}

# ================================================
# FEATURE: SHARED CORE (foundation tanpa feature spesifik)
# ================================================
collect_shared() {
    init_output "shared" "Shared Core (Layout, Providers, Hooks, Types)"

    section "📁" "APP ROOT"
    collect_file "$SRC/app/layout.tsx"
    collect_file "$SRC/app/page.tsx"
    collect_file "$SRC/app/globals.css"

    section "🎨" "LAYOUT COMPONENTS"
    collect_file "$SRC/components/layout/index.ts"
    collect_file "$SRC/components/layout/header.tsx"
    collect_file "$SRC/components/layout/app-sidebar.tsx"
    collect_file "$SRC/components/layout/mobile-nav.tsx"
    collect_file "$SRC/components/layout/user-menu.tsx"
    collect_file "$SRC/components/layout/nav-config.ts"

    section "🧩" "PROVIDERS"
    collect_file "$SRC/components/providers/index.ts"
    collect_file "$SRC/components/providers/auth-provider.tsx"
    collect_file "$SRC/components/providers/query-provider.tsx"

    section "🔧" "SHARED COMPONENTS"
    collect_file "$SRC/components/shared/index.ts"
    collect_file "$SRC/components/shared/confirm-dialog.tsx"
    collect_file "$SRC/components/shared/loading-spinner.tsx"
    collect_file "$SRC/components/shared/offline-detector.tsx"

    section "🎣" "CORE HOOKS"
    collect_file "$SRC/hooks/index.ts"
    collect_file "$SRC/hooks/use-auth.ts"
    collect_file "$SRC/hooks/use-is-desktop.ts"

    section "🗄️" "SUPABASE LIB"
    collect_file "$SRC/lib/supabase/client.ts"
    collect_file "$SRC/lib/supabase/server.ts"
    collect_file "$SRC/lib/supabase/admin.ts"
    collect_file "$SRC/lib/supabase/proxy.ts"

    section "🔀" "PROXY"
    collect_file "$SRC/proxy.ts"

    section "📚" "LIB & UTILS"
    collect_file "$SRC/lib/utils.ts"
    collect_file "$SRC/lib/query-client.ts"
    collect_file "$SRC/lib/auth-guard.ts"

    section "📝" "TYPES"
    collect_file "$SRC/types/index.ts"
    collect_file "$SRC/types/database.ts"

    section "⚙️" "CONSTANTS"
    collect_file "$SRC/constants/index.ts"
    collect_file "$SRC/constants/routes.ts"

    section "🗃️" "STORES"
    collect_file "$SRC/stores/index.ts"
    collect_file "$SRC/stores/auth-store.ts"

    print_summary "shared"
}

# ================================================
# ALL FEATURES (run all)
# ================================================
collect_all() {
    echo -e "${BOLD}${MAGENTA}🎯 Collecting ALL features (5 separate files)...${NC}"
    echo ""
    collect_admin
    collect_user
    collect_rapor
    collect_auth
    collect_shared
    echo ""
    echo -e "${BOLD}${GREEN}🎉 ALL DONE — 5 collection files generated:${NC}"
    ls -la "$COLLECTION_DIR"/collected-*.txt 2>/dev/null
}

# ================================================
# INTERACTIVE MENU
# ================================================
show_menu() {
    clear
    echo -e "${BOLD}${MAGENTA}╔═══════════════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}${MAGENTA}║   E-RAPORT PER-FEATURE COLLECTOR                  ║${NC}"
    echo -e "${BOLD}${MAGENTA}╚═══════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${CYAN}Pilih feature yang mau di-collect:${NC}"
    echo ""
    echo -e "  ${BOLD}1)${NC} ${YELLOW}🏫 ADMIN${NC}        — Master Data, Akademik, Sistem"
    echo -e "  ${BOLD}2)${NC} ${YELLOW}📝 USER${NC}         — Penilaian / Input Nilai harian"
    echo -e "  ${BOLD}3)${NC} ${YELLOW}📊 RAPOR${NC}        — Cetak / Preview / ZIP archive"
    echo -e "  ${BOLD}4)${NC} ${YELLOW}🔐 AUTH${NC}         — Login flow + session"
    echo -e "  ${BOLD}5)${NC} ${YELLOW}🧩 SHARED CORE${NC}  — Layout, providers, hooks dasar, types"
    echo -e "  ${BOLD}6)${NC} ${GREEN}🎯 ALL${NC}          — Generate semua (5 file terpisah)"
    echo -e "  ${BOLD}0)${NC} ${RED}❌ EXIT${NC}"
    echo ""
    echo -ne "${BOLD}Pilih [0-6]:${NC} "
}

# ================================================
# MAIN
# ================================================

# Mode CLI: argument langsung
if [ $# -gt 0 ]; then
    case "$1" in
        admin)   collect_admin ;;
        user)    collect_user ;;
        rapor)   collect_rapor ;;
        auth)    collect_auth ;;
        shared)  collect_shared ;;
        all)     collect_all ;;
        *)
            echo -e "${RED}❌ Unknown feature: $1${NC}"
            echo ""
            echo -e "Usage: ${BOLD}$0${NC} [admin|user|rapor|auth|shared|all]"
            echo -e "       (no argument = interactive menu)"
            exit 1
            ;;
    esac
    exit 0
fi

# Mode interactive
while true; do
    show_menu
    read -r choice
    case "$choice" in
        1) collect_admin; break ;;
        2) collect_user; break ;;
        3) collect_rapor; break ;;
        4) collect_auth; break ;;
        5) collect_shared; break ;;
        6) collect_all; break ;;
        0)
            echo -e "${YELLOW}👋 Bye${NC}"
            exit 0
            ;;
        *)
            echo -e "${RED}❌ Pilihan tidak valid. Tekan Enter untuk lanjut...${NC}"
            read -r
            ;;
    esac
done